# Generated by Django 4.2.6 on 2023-10-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
