# Generated by Django 4.2.5 on 2023-10-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category_id',
        ),
    ]
